from django.db import models

from apps.data.models import SecureToken

# Create your models here.
class AmzTokens(models.Model):
    USER = models.TextField()
    PROFILE_ID = models.TextField()
    PROFILE_NAME = models.TextField()
    REFRESH_TOKEN = SecureToken()
    LAST_UPDATED = models.DateTimeField()

class AmzScheduledReports(models.Model):
    USER = models.TextField()
    PROFILE_ID = models.TextField()
    REPORT_ENDPOINT = models.TextField(default='_')
    REPORT_ID = models.TextField()
    REPORT_DATE = models.IntegerField()
    GOOGLE_SHEET_ID = models.TextField()
    DATE_SCHEDULED = models.DateTimeField()

class AmzSponsoredProductsAds(models.Model):
    CAMPAIGN_ID = models.TextField()
    CAMPAIGN_NAME = models.TextField()
    CAMPAIGN_STATUS = models.TextField()
    AD_GROUP_ID = models.TextField()
    AD_GROUP_NAME = models.TextField()
    ASIN = models.TextField()
    SKU = models.TextField()
    IMPRESSIONS = models.IntegerField()
    CLICKS = models.IntegerField()
    COST = models.DecimalField(max_digits=12, decimal_places=2)
    CAMPAIGN_BUDGET = models.DecimalField(max_digits=12, decimal_places=2)
    CAMPAIGN_BUDGET_TYPE = models.TextField()
    CURRENCY = models.TextField()
    ATTRIBUTED_SALES_1D = models.DecimalField(max_digits=12, decimal_places=2)
    ATTRIBUTED_SALES_7D = models.DecimalField(max_digits=12, decimal_places=2)
    ATTRIBUTED_SALES_14D = models.DecimalField(max_digits=12, decimal_places=2)
    ATTRIBUTED_SALES_30D = models.DecimalField(max_digits=12, decimal_places=2)
    ATTRIBUTED_SALES_1D_SAME_SKU = models.DecimalField(max_digits=12, decimal_places=2)
    ATTRIBUTED_SALES_7D_SAME_SKU = models.DecimalField(max_digits=12, decimal_places=2)
    ATTRIBUTED_SALES_14D_SAME_SKU = models.DecimalField(max_digits=12, decimal_places=2)
    ATTRIBUTED_SALES_30D_SAME_SKU = models.DecimalField(max_digits=12, decimal_places=2)
    ATTRIBUTED_UNITS_ORDERED_1D = models.IntegerField()
    ATTRIBUTED_UNITS_ORDERED_7D = models.IntegerField()
    ATTRIBUTED_UNITS_ORDERED_14D = models.IntegerField()
    ATTRIBUTED_UNITS_ORDERED_30D = models.IntegerField()
    ATTRIBUTED_UNITS_ORDERED_1D_SAME_SKU = models.IntegerField()
    ATTRIBUTED_UNITS_ORDERED_7D_SAME_SKU = models.IntegerField()
    ATTRIBUTED_UNITS_ORDERED_14D_SAME_SKU = models.IntegerField()
    ATTRIBUTED_UNITS_ORDERED_30D_SAME_SKU = models.IntegerField()
    ATTRIBUTED_CONVERSIONS_1D = models.IntegerField()
    ATTRIBUTED_CONVERSIONS_7D = models.IntegerField()
    ATTRIBUTED_CONVERSIONS_14D = models.IntegerField()
    ATTRIBUTED_CONVERSIONS_30D = models.IntegerField()
    ATTRIBUTED_CONVERSIONS_1D_SAME_SKU = models.IntegerField()
    ATTRIBUTED_CONVERSIONS_7D_SAME_SKU = models.IntegerField()
    ATTRIBUTED_CONVERSIONS_14D_SAME_SKU = models.IntegerField()
    ATTRIBUTED_CONVERSIONS_30D_SAME_SKU = models.IntegerField()
    DATE = models.IntegerField()
    DATE_UPLOADED = models.DateTimeField()