# Generated by Django 3.2.13 on 2022-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.TextField()),
                ('EMAIL', models.TextField()),
                ('COMPANY', models.TextField()),
                ('LAST_UPDATED', models.DateTimeField()),
            ],
        ),
    ]
