# Generated by Django 3.2.13 on 2022-07-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_newslettersignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersignup',
            old_name='LAST_UPDATED',
            new_name='SIGNUP_DATE',
        ),
    ]
