# Generated by Django 3.2.13 on 2022-06-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmzTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('PROFILE_ID', models.TextField()),
                ('PROFILE_NAME', models.TextField()),
                ('REFRESH_TOKEN', models.TextField()),
                ('LAST_UPDATED', models.DateTimeField()),
            ],
        ),
    ]
