# Generated by Django 3.2.13 on 2022-06-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmzScheduledReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('PROFILE_ID', models.TextField()),
                ('REPORT_ID', models.TextField()),
                ('REPORT_DATE', models.IntegerField()),
                ('GOOGLE_SHEET_ID', models.TextField()),
                ('DATE_SCHEDULED', models.DateTimeField()),
            ],
        ),
    ]
