# Generated by Django 3.2.13 on 2022-07-03 03:06

import apps.data.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_api', '0002_amzscheduledreports_report_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amztokens',
            name='REFRESH_TOKEN',
            field=apps.data.models.SecureToken(),
        ),
    ]
