# Generated by Django 3.2.13 on 2022-06-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_api', '0002_amzscheduledreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='amzscheduledreports',
            name='GOOGLE_SHEET_ID',
            field=models.TextField(),
        ),
    ]
