# Generated by Django 3.2.13 on 2022-07-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_api', '0005_amzsponsoredproductsads_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='amzsponsoredproductsads',
            name='REPORT_ID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
