# Generated by Django 3.2.13 on 2022-07-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_api', '0006_amzsponsoredproductsads_report_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmzSponsoredProductsKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPORT_ID', models.TextField()),
                ('AD_GROUP_ID', models.TextField()),
                ('AD_GROUP_NAME', models.TextField()),
                ('CURRENCY', models.TextField()),
                ('CAMPAIGN_BUDGET', models.DecimalField(decimal_places=2, max_digits=12)),
                ('CAMPAIGN_BUDGET_TYPE', models.TextField()),
                ('CAMPAIGN_ID', models.TextField()),
                ('CAMPAIGN_NAME', models.TextField()),
                ('CAMPAIGN_STATUS', models.TextField()),
                ('IMPRESSIONS', models.IntegerField()),
                ('CLICKS', models.IntegerField()),
                ('COST', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ATTRIBUTED_SALES_1D', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ATTRIBUTED_SALES_7D', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ATTRIBUTED_SALES_14D', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ATTRIBUTED_SALES_30D', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ATTRIBUTED_SALES_1D_SAME_SKU', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ATTRIBUTED_SALES_7D_SAME_SKU', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ATTRIBUTED_SALES_14D_SAME_SKU', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ATTRIBUTED_SALES_30D_SAME_SKU', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ATTRIBUTED_UNITS_ORDERED_1D', models.IntegerField()),
                ('ATTRIBUTED_UNITS_ORDERED_7D', models.IntegerField()),
                ('ATTRIBUTED_UNITS_ORDERED_14D', models.IntegerField()),
                ('ATTRIBUTED_UNITS_ORDERED_30D', models.IntegerField()),
                ('ATTRIBUTED_UNITS_ORDERED_1D_SAME_SKU', models.IntegerField()),
                ('ATTRIBUTED_UNITS_ORDERED_7D_SAME_SKU', models.IntegerField()),
                ('ATTRIBUTED_UNITS_ORDERED_14D_SAME_SKU', models.IntegerField()),
                ('ATTRIBUTED_UNITS_ORDERED_30D_SAME_SKU', models.IntegerField()),
                ('KEYWORD_TEXT', models.TextField()),
                ('MATCH_TYPE', models.TextField()),
                ('QUERY', models.TextField()),
                ('ATTRIBUTED_CONVERSIONS_1D', models.IntegerField()),
                ('ATTRIBUTED_CONVERSIONS_7D', models.IntegerField()),
                ('ATTRIBUTED_CONVERSIONS_14D', models.IntegerField()),
                ('ATTRIBUTED_CONVERSIONS_30D', models.IntegerField()),
                ('ATTRIBUTED_CONVERSIONS_7D_SAME_SKU', models.IntegerField()),
                ('ATTRIBUTED_CONVERSIONS_14D_SAME_SKU', models.IntegerField()),
                ('ATTRIBUTED_CONVERSIONS_1D_SAME_SKU', models.IntegerField()),
                ('ATTRIBUTED_CONVERSIONS_30D_SAME_SKU', models.IntegerField()),
                ('DATE', models.IntegerField()),
                ('DATE_UPLOADED', models.DateTimeField()),
            ],
        ),
    ]
