# Generated by Django 3.2.13 on 2022-07-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_api', '0007_amzsponsoredproductskeywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amzscheduledreports',
            name='REPORT_ID',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='amzsponsoredproductsads',
            name='REPORT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_api.amzscheduledreports', to_field='REPORT_ID'),
        ),
        migrations.AlterField(
            model_name='amzsponsoredproductskeywords',
            name='REPORT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_api.amzscheduledreports', to_field='REPORT_ID'),
        ),
    ]
