# Generated by Django 3.2.13 on 2022-07-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsMaintained',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('AMAZON_PROFILE_ID', models.TextField()),
                ('AMAZON_PROFILE_NAME', models.TextField()),
                ('AMAZON_ENDPOINT', models.TextField()),
                ('REPORT_NAME', models.TextField()),
                ('GOOGLE_SHEETS_ID', models.TextField()),
                ('GOOGLE_SHEETS_FILE_NAME', models.TextField()),
                ('GOOGLE_SHEETS_TAB_NAME', models.TextField()),
                ('DATE_CREATED', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportsRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER', models.TextField()),
                ('AMAZON_PROFILE_ID', models.TextField()),
                ('AMAZON_PROFILE_NAME', models.TextField()),
                ('AMAZON_ENDPOINT', models.TextField()),
                ('GOOGLE_SHEETS_ID', models.TextField()),
                ('GOOGLE_SHEETS_FILE_NAME', models.TextField()),
                ('GOOGLE_SHEETS_TAB_NAME', models.TextField()),
                ('ENDPOINT_EVALUATION_DATE', models.IntegerField()),
                ('STATUS', models.TextField()),
                ('DATE_ENDPOINT_QUERIED', models.DateTimeField()),
                ('DATE_GOOGLE_SHEETS_UPDATED', models.DateTimeField()),
            ],
        ),
    ]
